name: Daily Plant ID Reset

  on:
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch:

  jobs:
    reset-identifications:
      runs-on: ubuntu-latest

      steps:
        - name: Call Daily Reset Function
          run: |
            curl -L -X POST \
              'https://ztpuninaxtazpanepmpj.supabase.co/functions/v1/Daily-identi    
  fication-reset' \
              -H 'Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}'    
   \
              -H 'Content-Type: application/json' \
              -d '{}'
